### ISSUE TITLE
Query for blob failed

### ISSUE THREAD

**Issue by cluzier** [SV3A/bBucket2gHub#11]
Hello, I've created and added my credentials to the .env file and ran the program. I see that the program is working by reading the private repositories from my bitbucket workspace but then the program fails with this error:

```/Users/user/Desktop/bBucket2gHub/src/github/github-push.js:69
            throw new Error("Query for blob failed");
                  ^

Error: Query for blob failed
    at GithubPusher._queryBlobSha (/Users/user/Desktop/bBucket2gHub/src/github/github-push.js:69:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GithubPusher._getOrInitShadowContent (/Users/user/Desktop/bBucket2gHub/src/github/github-push.js:136:22)
    at async GithubPusher.sync (/Users/user/Desktop/bBucket2gHub/src/github/github-push.js:167:29)
    at async main (/Users/user/Desktop/bBucket2gHub/src/index.js:27:5)```
    
Is there any way to fix this issue? Any help is appreciated.

**Comment by cluzier** [comment]
Closing this issue; I did not have the GitHub Owner credential filled out in the .env file.
